server:
  port: 801
  
  
eureka:
  client:
    register-with-eureka: false #当前的服务不注册到eureke消费端
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ 